name: camelapp
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  font_awesome_flutter: ^10.1.0
  image_picker:
  firebase_core: ^1.22.0
  firebase_database: ^9.1.4
  firebase_storage: ^10.3.8


  
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/images/Logo.png


 
  fonts:
    - family: DINNextLTArabic
      fonts:
        - asset: assets/fonts/DINNextLTArabic-Regular-4.ttf
          weight: 400
 
